#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/stockmonitorsystem?useSSL=false&serverTimezone=Asia/Shanghai
#    username: root
#    password: root

spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://124.223.67.235:3306/stock?useSSL=false&serverTimezone=Asia/Shanghai
#    username: root
#    password: root

  shardingsphere:
    datasource:
      names:
        master,slave

      master:
        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://124.223.67.235:3306/testcopy?useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: root

      slave:
        type: com.alibaba.druid.pool.DruidDataSource
#          driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://121.4.40.195:3306/testcopy?useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: password

    masterslave:
      load-balance-algorithm-type: round_robin
      name: dataSource
      master-data-source-name: master
      slave-data-source-names: slave

  main:
    allow-bean-definition-overriding: true

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 8
        max-wait: 1ms
        max-idle: 4
        min-idle: 0

mybatis:
  type-aliases-package: com.example.stocksystem.entity
  mapper-locations: com/example/stocksystem/dao/*.xml
  configuration:
    map-underscore-to-camel-case: true
mybatis-plus:
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

